### ISSUE TITLE
Check that version is not changed

### ISSUE THREAD

**Issue by naterush** [mito-ds/mitosheet_helper_config#12]
https://github.com/mito-ds/mitosheet_helper_config/blob/7cc9ee048f562c56725b0ac7b112b461b2619215/mitosheet_helper_config/mito_config.py#L14

Can you just an an assert to the bottom of this file that checks the version is equal to 1? So that users really know not to change it!

**Comment by aarondr77** [comment]
Resolved in 867e89aa09a4ea5bad3b81fb8600455673c2521a
